#!/usr/bin/env bash

yaba -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Tiling
yabai -m config layout bsp
yabai -m config window_placement second_child

# Padding
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 2
yabai -m config window_shadow off

# Mouse
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Parallels Desktop$" manage=off

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
	yabai -m space --destroy
done

function setup_space {
	local idx="$1"
	local name="$2"
	local space=
	echo "setup space $idx : $name"

	space=$(yabai -m query --spaces --space "$idx")
	if [ -z "$space" ]; then
		yabai -m space --create
	fi

	yabai -m space "$idx" --label "$name"
}

setup_space 1 one
setup_space 2 two
setup_space 3 three
setup_space 4 four
setup_space 5 five
setup_space 6 six
setup_space 7 seven
setup_space 8 eight
setup_space 9 nine
setup_space 10 ten

# Style
borders active_color=gradient(top_left=0xff98c379,bottom_right=0xee61afef) inactive_color=0x5c637054 width=2.0 hidpi=true &
