#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	ssh_name=$1
elif [[ $# -eq 0 ]]; then
	$HOME/.local/scripts/tssh-select.sh
else
	tmux display-message -d 500 "This script expects zero or one argument."
	sleep 1
	tmux display-message -d 500 "This script expects zero or one argument."
	sleep 1
	tmux display-message -d 5000 "This script expects zero or one argument."
fi
