#!/usr/bin/env bash

source "$(dirname "$0")/../lib/utils.sh"

install ansible ansible-lint eza fzf go:golang lua:lua5.4 neovim nodejs npm rustup unzip

stow -d $HOME/.dotfiles/configs/ -t $HOME/ gh git nvim
