#!/usr/bin/env bash

source "$(dirname "$0")/../lib/utils.sh"

install jq stow zsh zoxide
install_with_fallback eza "cargo install eza"
install_with_fallback starship "curl -sS https://starship.rs/install.sh | sh"
